# Generated by Django 6.0.7 on 2026-07-20 11:25

import apps.storage.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.storage.models.get_unique_upload_path, verbose_name='Файл')),
                ('filename', models.CharField(max_length=255, verbose_name='Имя файла')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('size', models.BigIntegerField(verbose_name='Размер в байтах')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('last_downloaded_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата последнего скачивания')),
                ('path_in_storage', models.CharField(blank=True, max_length=500, verbose_name='Путь к файлу в хранилище')),
                ('special_link', models.CharField(blank=True, max_length=500, verbose_name='Специальная обезличенная ссылка')),
                ('share_token', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
        ),
    ]
