# Generated by Django 6.0.7 on 2026-07-20 13:34

import apps.storage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfile',
            name='file',
            field=models.FileField(upload_to=apps.storage.models.get_unique_upload_path, verbose_name='Физический файл на диске'),
        ),
        migrations.AlterField(
            model_name='userfile',
            name='filename',
            field=models.CharField(max_length=255, verbose_name='Оригинальное имя файла'),
        ),
        migrations.AlterField(
            model_name='userfile',
            name='last_downloaded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последняя дата скачивания'),
        ),
        migrations.AlterField(
            model_name='userfile',
            name='size',
            field=models.BigIntegerField(verbose_name='Размер файла в байтах'),
        ),
    ]
